### ISSUE TITLE
Threading does not seem to work.

### ISSUE THREAD

**Issue by blandyuk** [cyclone-github/magento_cracker#1]
Hi,

When using "magento_v2_argon2id_threaded.py", says I'm only using 1 thread.
I don't get any status updates either.
Best having an option to specify number of threads, example: -threads 10

Using Python 3.10.9 on Win10.

**Comment by blandyuk** [comment]
Ah! It's one thread per hash, got it.

**Comment by blandyuk** [comment]
I did close this issue, but re-opened as it could be optimized by threading the wordlist chunks for a single hash. This would be better, as these hashes are slow, so we would mainly be working on one at-a-time.

**Comment by cyclone-github** [comment]
Yes, the code logic is to run 1x thread per hash up to the available CPU threads (as stated in the code comments). I wrote the multi-threaded version as a proof-of-concept for running a multiple hash test set, but as you stated, it is not optimized for running a single hash. Moving forward, my focus will be on porting the code to Go. This is due to even if the Python3 code is better optimized, it will still be slow. :)
