### ISSUE TITLE
v1 magento hashes

### ISSUE THREAD

**Issue by ghost** [cyclone-github/magento_cracker#3]
What about version 1 hashes? They end with `:1` and look like that:

`0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef:ABCDEFGHIJKLMNOPQRSTUVWXYZ012345:1`

Aren't they argon2?

I believe they are still Magento 2 because Magento 1 used MD5.

**Comment by cyclone-github** [comment]
AFAIK, Magento hashes formatted as `hash:salt:1` should be not be Argon. 

If you do have argon hashes formatted as `hash:salt:1`, you can change the following line to support them. https://github.com/cyclone-github/magento_cracker/blob/3ffed61c0ee29e92416ec8ecfd5876df21c599a1/magento_v2_argon2id_threaded.py#L52 change to:
`if version == "1" or version == "2" or version == "3":`
or a more concise version:
`if version in ("1", "2", "3"):`

Since the `hash:salt:1`  formatting is not confirmed to be Magento argon, it will not be implemented into the codebase.
